# config
server_port: 8009
server_host: "0.0.0.0"

pgsql: "postgresql://test:123456@127.0.0.1:5432/cs_cdp"

timeplus: "timeplus://test:123456@127.0.0.1:8123/default"
# PORT NOT 8463

static_path: "http://127.0.0.1:8009/"

model_name: "qwen-max"
# glm-4
# deepseek-chat
# qwen-max
# gpt-4o-mini

model_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
# https://open.bigmodel.cn/api/paas/v4/
# https://api.deepseek.com/v1/
# https://dashscope.aliyuncs.com/compatible-mode/v1
# https://api.openai.com/v1
